import { type CompanySitePackages } from "~/types/companySitePackages";
export const companySitePackages: CompanySitePackages[] = [
  {
    id: 1,
    item: "بهینه شده برای تمامی دستگاه های دیجیتال",
    bronze: true,
    silver: true,
    gold: true,
  },
  {
    id: 2,
    item: "ساخت صفحات متفاوت به خواست شما",
    bronze: true,
    silver: true,
    gold: true,
  },
  {
    id: 3,
    item: "کاملا ریسپانسیو برای دستگاه موبایل",
    bronze: true,
    silver: true,
    gold: true,
  },
  {
    id: 4,
    item: "دسترسی کامل به پنل ادمین",
    bronze: true,
    silver: true,
    gold: true,
  },
  {
    id: 5,
    item: "استفاده از قالب و طراحی اختصاصی ",
    bronze: true,
    silver: true,
    gold: true,
  },
  {
    id: 6,
    item: "پشتیبانی یکساله سرعت و امنیت رایگان",
    bronze: true,
    silver: true,
    gold: true,
  },
  {
    id: 7,
    item: "دامنه ir رایگان",
    bronze: true,
    silver: true,
    gold: true,
  },
  {
    id: 8,
    item: "ثبت لوکیشن در گوگل و تمامی مسیریاب ها",
    bronze: true,
    silver: true,
    gold: true,
  },
  {
    id: 9,
    item: "فروشگاه با فیلتر محصولات اختصاصی",
    bronze: true,
    silver: true,
    gold: true,
  },
  {
    id: 10,
    item: "درج گوگل سرچ کنسول و معرفی به گوگل",
    bronze: true,
    silver: true,
    gold: true,
  },
  {
    id: 11,
    item: "دریافت اینماد و درگاه بانکی",
    bronze: true,
    silver: true,
    gold: true,
  },
  {
    id: 12,
    item: "پنل ثبت نام کاربر عمده و جزء",
    bronze: false,
    silver: true,
    gold: true,
  },
  {
    id: 13,
    item: "تولید محتوا اولیه رایگان",
    bronze: false,
    silver: true,
    gold: true,
  },
  {
    id: 14,
    item: "ساخت ایمیل اختصاصی با دامین سایت",
    bronze: false,
    silver: true,
    gold: true,
  },
  {
    id: 15,
    item: "ایجاد صفحه‌در آپارات",
    bronze: false,
    silver: false,
    gold: true,
  },
  {
    id: 16,
    item: "چت آنلاین با کاربران",
    bronze: false,
    silver: false,
    gold: true,
  },
  {
    id: 17,
    item: "دریافت گواهینامه ی SSL",
    bronze: false,
    silver: false,
    gold: true,
  },
  {
    id: 18,
    item: "ایجاد باشگاه مشتریان",
    bronze: false,
    silver: false,
    gold: true,
  },
  {
    id: 19,
    item: "لینک سازی در صفحات اجتماعی و اتصال به اینستاگرام",
    bronze: false,
    silver: false,
    gold: true,
  },
  {
    id: 20,
    item: "پشتیبانی تا اولین فروش سایت",
    bronze: false,
    silver: false,
    gold: true,
  },
  {
    id: 21,
    item: "ایجاد کمپین فروش در کمترین زمان",
    bronze: false,
    silver: false,
    gold: false,
  },
  {
    id: 22,
    item: "نوبت دهی آنلاین برای مشتریان",
    bronze: false,
    silver: false,
    gold: false,
  },
  {
    id: 23,
    item: "طراحی بنر اختصاصی و مناسبتی",
    bronze: false,
    silver: false,
    gold: false,
  },
  {
    id: 24,
    item: "ساخت پنل پیامکی و اتصال به سایت",
    bronze: false,
    silver: false,
    gold: false,
  },
];
